parameters:
    swarrot_extension.retry_config_queues:
        exchanges:
            internal_waiting_5:
                type: 'topic'
                durable: true
            internal_waiting_10:
                type: 'topic'
                durable: true
            internal_waiting_30:
                type: 'topic'
                durable: true
            internal_waiting_60:
                type: 'topic'
                durable: true
            internal_waiting_600:
                type: 'topic'
                durable: true

        queues:
            internal_waiting_5:
                durable: true
                arguments:
                    x-message-ttl: 5000
                    x-dead-letter-exchange: ""
                bindings:
                    - exchange: "internal_waiting_5"
                      routing_key: "#"
            internal_waiting_10:
                durable: true
                arguments:
                    x-message-ttl: 10000
                    x-dead-letter-exchange: ""
                bindings:
                    - exchange: "internal_waiting_10"
                      routing_key: "#"
            internal_waiting_30:
                durable: true
                arguments:
                    x-message-ttl: 30000
                    x-dead-letter-exchange: ""
                bindings:
                    - exchange: "internal_waiting_30"
                      routing_key: "#"
            internal_waiting_60:
                durable: true
                arguments:
                    x-message-ttl: 60000
                    x-dead-letter-exchange: ""
                bindings:
                    - exchange: "internal_waiting_60"
                      routing_key: "#"
            internal_waiting_600:
                durable: true
                arguments:
                    x-message-ttl: 600000
                    x-dead-letter-exchange: ""
                bindings:
                    - exchange: "internal_waiting_600"
                      routing_key: "#"

services:
    swarrot_extension.processor.abstract:
        class: Ensembl260\SwarrotExtensionBundle\Broker\Processor\Processor
        abstract: true
        arguments:
            - 'replaced_by_BrokerProcessorPass'
            - '@validator'

    swarrot_extension.processor.doctrine_document_manager:
        class: Swarrot\SwarrotBundle\Processor\Doctrine\ObjectManagerProcessorConfigurator
        arguments:
            - 'Swarrot\Processor\Doctrine\ObjectManagerProcessor'
            - '@?doctrine_mongodb'

    swarrot_extension.processor.x_death_max_count:
        class: Ensembl260\SwarrotExtensionBundle\Broker\Processor\Configurator\XDeathMaxCountProcessorConfigurator
        arguments:
            - 'Swarrot\Processor\XDeath\XDeathMaxCountProcessor'
            - '@swarrot_extension.processor.callback.x_death_max_count_exception_handler'

    swarrot_extension.processor.x_death_max_lifetime:
        class: Ensembl260\SwarrotExtensionBundle\Broker\Processor\Configurator\XDeathMaxLifetimeProcessorConfigurator
        arguments:
            - 'Swarrot\Processor\XDeath\XDeathMaxLifetimeProcessor'
            - '@swarrot_extension.processor.callback.x_death_max_lifetime_exception_handler'

    swarrot_extension.processor.callback.x_death_max_count_exception_handler:
        class: Ensembl260\SwarrotExtensionBundle\Broker\Processor\Callback\XDeathMaxCountExceptionHandler
        arguments:
            - '@event_dispatcher'

    swarrot_extension.processor.callback.x_death_max_lifetime_exception_handler:
        class: Ensembl260\SwarrotExtensionBundle\Broker\Processor\Callback\XDeathMaxLifetimeExceptionHandler
        arguments:
            - '@event_dispatcher'

    swarrot_extension.publisher.json_serializer:
        class: Ensembl260\SwarrotExtensionBundle\Broker\Publisher\JsonSerializer

    swarrot_extension.publisher.message_factory:
        alias: swarrot_extension.publisher.message_factory.default

    swarrot_extension.publisher.message_factory.default:
        class: Ensembl260\SwarrotExtensionBundle\Broker\Publisher\MessageFactory

    swarrot_extension.publisher:
        class: Ensembl260\SwarrotExtensionBundle\Broker\Publisher\Publisher
        arguments:
            - '@swarrot.publisher'
            - '@swarrot_extension.message_factory'

    swarrot_extension.error_publisher.default:
        class: Ensembl260\SwarrotExtensionBundle\Broker\Publisher\ErrorPublisher
        arguments:
            - '@swarrot_extension.publisher'
            - '%swarrot_extension.error_publisher.routing_key_pattern%'
            - '@swarrot_extension.publisher.json_serializer'

    swarrot_extension.event_subscriber.x_death_error_publisher:
        class: Ensembl260\SwarrotExtensionBundle\EventSubscriber\XDeathErrorPublisherSubscriber
        arguments:
            - '@swarrot_extension.error.publisher'
        tags:
            - { name: kernel.event_subscriber }

    swarrot_extension.command.vhost_mapping_create:
        class: Ensembl260\SwarrotExtensionBundle\Command\VhostMappingCreateCommand
        arguments:
            - '%swarrot_extension.admin_connection.host%'
            - '%swarrot_extension.admin_connection.port%'
            - '%swarrot_extension.admin_connection.login%'
            - '%swarrot_extension.admin_connection.password%'
            - '%swarrot_extension.retry_config_queues%'
        tags:
            - { name: console.command }
