language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

php:
  - '7.3'
  - '7.4'

env:
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=4.0.*
  - SYMFONY_VERSION=4.1.*
  - SYMFONY_VERSION=4.2.*
  - SYMFONY_VERSION=4.3.*
  - SYMFONY_VERSION=4.4.*
  - SYMFONY_VERSION=5.0.*

before_install:
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer update --no-interaction --prefer-dist

script:
  - composer validate --strict --no-check-lock
  - ./vendor/bin/phpunit
